import { ShopItem } from "@/types/shop";

export const SHOP_CATALOG: ShopItem[] = [
  {
    id: "bronze-frame",
    name: "Bronze Frame",
    description: "A polished bronze border signifying the beginning of an epic adventure.",
    type: "frame",
    rarity: "Common",
    price: 100,
    icon: "Shield",
    accentColor: "#CD7F32",
    previewClass: "border-2 border-[#CD7F32] shadow-[0_0_10px_rgba(205,127,50,0.3)]",
  },
  {
    id: "neon-badge",
    name: "Neon Adventurer Badge",
    description: "An illuminated insignia awarded to dedicated quest seekers.",
    type: "badge",
    rarity: "Common",
    price: 150,
    icon: "Award",
    accentColor: "#22C55E",
    previewClass: "text-[#22C55E] drop-shadow-[0_0_8px_rgba(34,197,94,0.5)]",
  },
  {
    id: "cyber-ring",
    name: "Neon Avatar Ring",
    description: "A pulsating cyan energy halo circling your digital avatar.",
    type: "frame",
    rarity: "Rare",
    price: 300,
    icon: "CircleDot",
    accentColor: "#06B6D4",
    previewClass: "ring-4 ring-[#06B6D4] ring-offset-2 ring-offset-[#05060A] shadow-[0_0_20px_rgba(6,182,212,0.6)]",
  },
  {
    id: "synthwave-theme",
    name: "Synthwave Sunset Theme",
    description: "Imbues your dashboard with retrowave neon magenta and cyan highlights.",
    type: "theme",
    rarity: "Rare",
    price: 450,
    icon: "Palette",
    accentColor: "#EC4899",
    previewClass: "bg-gradient-to-r from-pink-500 via-purple-500 to-cyan-500 text-white",
  },
  {
    id: "cyber-knight-theme",
    name: "Cyber Knight Theme",
    description: "High-tech violet and gold armor stylings for disciplined heroes.",
    type: "theme",
    rarity: "Epic",
    price: 750,
    icon: "Sparkles",
    accentColor: "#7C3AED",
    previewClass: "bg-gradient-to-r from-violet-600 via-indigo-600 to-amber-500 text-white",
  },
  {
    id: "void-armor-frame",
    name: "Void Armor Frame",
    description: "Dark matter crystalline plating etched with ancient runes.",
    type: "frame",
    rarity: "Epic",
    price: 900,
    icon: "Hexagon",
    accentColor: "#A855F7",
    previewClass: "border-2 border-purple-500 shadow-[0_0_25px_rgba(168,85,247,0.7)]",
  },
  {
    id: "cosmic-aura",
    name: "Cosmic Aura",
    description: "A celestial orbital nebula radiating star particles around your character.",
    type: "aura",
    rarity: "Legendary",
    price: 1500,
    icon: "Flame",
    accentColor: "#F59E0B",
    previewClass: "animate-pulse-glow ring-4 ring-amber-400 shadow-[0_0_35px_rgba(245,158,11,0.8)]",
  },
  {
    id: "chrono-core",
    name: "Chrono Singularity Core",
    description: "The ultimate relic. Bends spacetime and immortalizes your discipline.",
    type: "badge",
    rarity: "Legendary",
    price: 2500,
    icon: "Zap",
    accentColor: "#38BDF8",
    previewClass: "shadow-[0_0_40px_rgba(56,189,248,0.9)] text-sky-300",
  },
];

export function getShopItemById(id: string): ShopItem | undefined {
  return SHOP_CATALOG.find((item) => item.id === id);
}
